// Generated by npm run alta:script. Edit shared schema / handler, then regenerate.
// Source: Germán's “Ficha de Cliente”, cells C11:D22. Keep option labels verbatim.
const IVA_OPTIONS = ['Consumidor final', 'Monotributista', 'Responsable inscripto'];
const ADVISOR_OPTIONS = ['Matias Pricipato', 'Rodrigo Santillan', 'German Jimenez', 'Yamila Vazquez', 'Gerardo Miño', 'Jorge Monzon'];
const FIELDS = ['nombre', 'cuit', 'condicionIva', 'importador', 'origen', 'vieneDeCurso', 'curso', 'telefono', 'email', 'domicilio', 'contactoOperacion', 'contactoAdministracion', 'asesor'];
const HEADERS = ['ID de alta', 'Fecha y hora (UTC)', 'Entorno', 'Nombre, apellido o razón social (ARCA-AFIP)', 'CUIT/CUIL', 'Condición frente al IVA', 'Importador registrado en Aduana', 'Por dónde nos conocieron', 'Viene de un curso', 'Cuál curso', 'Teléfono', 'E-mail', 'Domicilio', 'Contacto para avances de la operación', 'Contacto para temas administrativos', 'Quién te asesoró', 'Huella de envío'];

function validateRegistration(input) {
  const data = Object.fromEntries(FIELDS.map(key => [key, typeof input?.[key] === 'string' ? input[key].trim() : '']));
  const errors = {};
  for (const key of FIELDS) {
    if (!['importador', 'curso'].includes(key) && !data[key]) errors[key] = 'Completá este dato.';
    if (data[key].length > (['domicilio', 'contactoOperacion', 'contactoAdministracion'].includes(key) ? 500 : 200)) errors[key] = 'El texto es demasiado largo.';
    if ([...data[key]].some(char => char.charCodeAt(0) < 32 && ![9, 10, 13].includes(char.charCodeAt(0)))) errors[key] = 'El texto contiene caracteres no válidos.';
  }
  if (!/^(?:\d{11}|\d{2}-\d{8}-\d)$/.test(data.cuit)) errors.cuit = 'Ingresá 11 dígitos, con o sin guiones.';
  data.cuit = data.cuit.replace(/-/g, '');
  if (/^\d{11}$/.test(data.cuit)) {
    const sum = [5,4,3,2,7,6,5,4,3,2].reduce((total, weight, i) => total + Number(data.cuit[i]) * weight, 0);
    const digit = 11 - sum % 11;
    if ((digit === 11 ? 0 : digit === 10 ? 9 : digit) !== Number(data.cuit[10])) errors.cuit = 'Revisá el CUIT/CUIL: el dígito verificador no coincide.';
  }
  if (!IVA_OPTIONS.includes(data.condicionIva)) errors.condicionIva = 'Elegí una condición frente al IVA.';
  if (data.condicionIva === 'Responsable inscripto') {
    if (!['Sí', 'No'].includes(data.importador)) errors.importador = 'Indicá si sos importador registrado.';
  } else data.importador = '';
  if (!['Sí', 'No'].includes(data.vieneDeCurso)) errors.vieneDeCurso = 'Elegí Sí o No.';
  if (data.vieneDeCurso === 'Sí' && !data.curso) errors.curso = 'Indicá el nombre del curso.';
  if (data.vieneDeCurso !== 'Sí') data.curso = '';
  data.email = data.email.toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) errors.email = 'Ingresá un e-mail válido.';
  if (!/^\+?[\d\s().-]+$/.test(data.telefono) || !/^\d{7,15}$/.test(data.telefono.replace(/\D/g, ''))) errors.telefono = 'Ingresá un teléfono válido, incluyendo código de área.';
  if (!ADVISOR_OPTIONS.includes(data.asesor)) errors.asesor = 'Elegí quién te asesoró.';
  return { data, errors, valid: Object.keys(errors).length === 0 };
}

// Dedicated standalone deployment. Never paste into the contact/newsletter project.
// Script Properties: ALTA_CLIENTES_SECRET, ALTA_CLIENTES_SHEET_ID.
function doGet() { return output_({ ok: false, error: 'method_not_allowed' }); }
function doPost(e) {
  try {
    const raw = e && e.postData && e.postData.contents;
    if (!raw || raw.length > 20000) return output_({ ok: false, error: 'invalid_body' });
    const envelope = JSON.parse(raw);
    const properties = PropertiesService.getScriptProperties();
    const secret = properties.getProperty('ALTA_CLIENTES_SECRET');
    if (!secret || secret.length < 32 || typeof envelope.message !== 'string' || !equal_(envelope.signature, hmac_(envelope.message, secret))) return output_({ ok: false, error: 'unauthorized' });
    const body = JSON.parse(envelope.message);
    if (!Number.isFinite(body.timestamp) || Math.abs(Date.now() - body.timestamp) > 300000 || !/^[a-f\d]{8}-(?:[a-f\d]{4}-){3}[a-f\d]{12}$/i.test(body.requestId || '') || !/^[a-f\d]{64}$/.test(body.clientKey || '') || !['preview', 'production'].includes(body.environment)) return output_({ ok: false, error: 'invalid_request' });
    const result = validateRegistration(body.data);
    if (!result.valid) return output_({ ok: false, error: 'validation' });
    const hash = hmac_(body.environment + ':' + JSON.stringify(result.data), secret);
    const lock = LockService.getScriptLock();
    if (!lock.tryLock(10000)) return output_({ ok: false, error: 'busy' });
    try {
      const sheet = SpreadsheetApp.openById(properties.getProperty('ALTA_CLIENTES_SHEET_ID')).getSheetByName('Hoja 1');
      if (!sheet || JSON.stringify(sheet.getRange(1, 1, 1, HEADERS.length).getValues()[0]) !== JSON.stringify(HEADERS)) return output_({ ok: false, error: 'schema_mismatch' });
      const last = sheet.getLastRow();
      if (last > 1) {
        const prior = sheet.getRange(2, 1, last - 1, 1).createTextFinder(body.requestId).matchEntireCell(true).findNext();
        if (prior) {
          const oldHash = sheet.getRange(prior.getRow(), HEADERS.length).getValue();
          return output_(oldHash === hash ? { ok: true, registrationId: body.requestId, duplicate: true } : { ok: false, error: 'idempotency_conflict' });
        }
        const matches = sheet.getRange(2, HEADERS.length, last - 1, 1).createTextFinder(hash).matchEntireCell(true).findAll();
        for (const match of matches) {
          const previous = sheet.getRange(match.getRow(), 1, 1, 2).getValues()[0];
          if (Date.now() - Date.parse(previous[1]) < 86400000) return output_({ ok: true, registrationId: previous[0], duplicate: true });
        }
      }
      // Cache is best-effort abuse protection; never the source of deduplication truth.
      const cache = CacheService.getScriptCache();
      const bucket = Math.floor(Date.now() / 600000);
      const keys = ['alta:ip:' + body.clientKey + ':' + bucket, 'alta:global:' + bucket];
      const counts = keys.map(key => Number(cache.get(key) || 0));
      if (counts[0] >= 10 || counts[1] >= 60) return output_({ ok: false, error: 'rate_limit' });
      keys.forEach((key, i) => cache.put(key, String(counts[i] + 1), 600));
      const d = result.data;
      const row = [body.requestId, new Date().toISOString(), body.environment, d.nombre, d.cuit, d.condicionIva, d.importador || 'No aplica', d.origen, d.vieneDeCurso, d.curso || 'No aplica', d.telefono, d.email, d.domicilio, d.contactoOperacion, d.contactoAdministracion, d.asesor, hash];
      if (last >= sheet.getMaxRows()) sheet.insertRowsAfter(last, 100);
      const range = sheet.getRange(last + 1, 1, 1, HEADERS.length);
      range.setNumberFormat('@');
      // Escape spreadsheet formulas while preserving identifiers and leading zeroes.
      range.setValues([row.map(value => /^[=+\-@']/.test(value) ? "'" + value : value)]);
      SpreadsheetApp.flush();
      const saved = range.getValues()[0];
      if (saved[0] !== body.requestId || saved[HEADERS.length - 1] !== hash) return output_({ ok: false, error: 'write_unconfirmed' });
      return output_({ ok: true, registrationId: body.requestId, duplicate: false });
    } finally { lock.releaseLock(); }
  } catch { return output_({ ok: false, error: 'persistence_unconfirmed' }); }
}
function hmac_(value, secret) { return Utilities.computeHmacSha256Signature(value, secret, Utilities.Charset.UTF_8).map(byte => ('0' + (byte & 255).toString(16)).slice(-2)).join(''); }
function equal_(a, b) { if (typeof a !== 'string' || a.length !== b.length) return false; let difference = 0; for (let i = 0; i < a.length; i++) difference |= a.charCodeAt(i) ^ b.charCodeAt(i); return difference === 0; }
function output_(payload) { return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON); }
