// Generated by npm run alta:script. Edit shared schema / handler / mail, then regenerate.
// Source: Germán's “Ficha de Cliente”, cells C11:D22. Keep option labels verbatim.
const IVA_OPTIONS = ['Consumidor final', 'Monotributista', 'Responsable inscripto'];
const ADVISOR_OPTIONS = ['Matias Pricipato', 'Rodrigo Santillan', 'German Jimenez', 'Yamila Vazquez', 'Gerardo Miño', 'Jorge Monzon'];
const FIELDS = ['nombre', 'cuit', 'condicionIva', 'importador', 'origen', 'vieneDeCurso', 'curso', 'telefono', 'email', 'domicilio', 'contactoOperacion', 'contactoAdministracion', 'asesor'];
const HEADERS = ['ID de alta', 'Fecha y hora (UTC)', 'Entorno', 'Nombre, apellido o razón social (ARCA-AFIP)', 'CUIT/CUIL', 'Condición frente al IVA', 'Importador registrado en Aduana', 'Por dónde nos conocieron', 'Viene de un curso', 'Cuál curso', 'Teléfono', 'E-mail', 'Domicilio', 'Contacto para avances de la operación', 'Contacto para temas administrativos', 'Quién te asesoró', 'Huella de envío'];

function validateRegistration(input) {
  const data = Object.fromEntries(FIELDS.map(key => [key, typeof input?.[key] === 'string' ? input[key].trim() : '']));
  const errors = {};
  for (const key of FIELDS) {
    if (!['importador', 'curso'].includes(key) && !data[key]) errors[key] = 'Completá este dato.';
    if (data[key].length > (['domicilio', 'contactoOperacion', 'contactoAdministracion'].includes(key) ? 500 : 200)) errors[key] = 'El texto es demasiado largo.';
    if ([...data[key]].some(char => char.charCodeAt(0) < 32 && ![9, 10, 13].includes(char.charCodeAt(0)))) errors[key] = 'El texto contiene caracteres no válidos.';
  }
  if (!/^(?:\d{11}|\d{2}-\d{8}-\d)$/.test(data.cuit)) errors.cuit = 'Ingresá 11 dígitos, con o sin guiones.';
  data.cuit = data.cuit.replace(/-/g, '');
  if (/^\d{11}$/.test(data.cuit)) {
    const sum = [5,4,3,2,7,6,5,4,3,2].reduce((total, weight, i) => total + Number(data.cuit[i]) * weight, 0);
    const digit = 11 - sum % 11;
    if ((digit === 11 ? 0 : digit === 10 ? 9 : digit) !== Number(data.cuit[10])) errors.cuit = 'Revisá el CUIT/CUIL: el dígito verificador no coincide.';
  }
  if (!IVA_OPTIONS.includes(data.condicionIva)) errors.condicionIva = 'Elegí una condición frente al IVA.';
  if (data.condicionIva === 'Responsable inscripto') {
    if (!['Sí', 'No'].includes(data.importador)) errors.importador = 'Indicá si sos importador registrado.';
  } else data.importador = '';
  if (!['Sí', 'No'].includes(data.vieneDeCurso)) errors.vieneDeCurso = 'Elegí Sí o No.';
  if (data.vieneDeCurso === 'Sí' && !data.curso) errors.curso = 'Indicá el nombre del curso.';
  if (data.vieneDeCurso !== 'Sí') data.curso = '';
  data.email = data.email.toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) errors.email = 'Ingresá un e-mail válido.';
  if (!/^\+?[\d\s().-]+$/.test(data.telefono) || !/^\d{7,15}$/.test(data.telefono.replace(/\D/g, ''))) errors.telefono = 'Ingresá un teléfono válido, incluyendo código de área.';
  if (!ADVISOR_OPTIONS.includes(data.asesor)) errors.asesor = 'Elegí quién te asesoró.';
  return { data, errors, valid: Object.keys(errors).length === 0 };
}

// Dedicated standalone deployment. Never paste into the contact/newsletter project.
// Script Properties: ALTA_CLIENTES_SECRET, ALTA_CLIENTES_SHEET_ID.
function doGet() { return output_({ ok: false, error: 'method_not_allowed' }); }
function doPost(e) {
  try {
    const raw = e && e.postData && e.postData.contents;
    if (!raw || raw.length > 20000) return output_({ ok: false, error: 'invalid_body' });
    const envelope = JSON.parse(raw);
    const properties = PropertiesService.getScriptProperties();
    const secret = properties.getProperty('ALTA_CLIENTES_SECRET');
    if (!secret || secret.length < 32 || typeof envelope.message !== 'string' || !equal_(envelope.signature, hmac_(envelope.message, secret))) return output_({ ok: false, error: 'unauthorized' });
    const body = JSON.parse(envelope.message);
    if (!Number.isFinite(body.timestamp) || Math.abs(Date.now() - body.timestamp) > 300000 || !/^[a-f\d]{8}-(?:[a-f\d]{4}-){3}[a-f\d]{12}$/i.test(body.requestId || '') || !/^[a-f\d]{64}$/.test(body.clientKey || '') || !['preview', 'production'].includes(body.environment)) return output_({ ok: false, error: 'invalid_request' });
    const result = validateRegistration(body.data);
    if (!result.valid) return output_({ ok: false, error: 'validation' });
    const hash = hmac_(body.environment + ':' + JSON.stringify(result.data), secret);
    const lock = LockService.getScriptLock();
    if (!lock.tryLock(10000)) return output_({ ok: false, error: 'busy' });
    try {
      const sheet = SpreadsheetApp.openById(properties.getProperty('ALTA_CLIENTES_SHEET_ID')).getSheetByName('Hoja 1');
      if (!sheet || JSON.stringify(sheet.getRange(1, 1, 1, HEADERS.length).getValues()[0]) !== JSON.stringify(HEADERS)) return output_({ ok: false, error: 'schema_mismatch' });
      const last = sheet.getLastRow();
      if (last > 1) {
        const prior = sheet.getRange(2, 1, last - 1, 1).createTextFinder(body.requestId).matchEntireCell(true).findNext();
        if (prior) {
          const oldHash = sheet.getRange(prior.getRow(), HEADERS.length).getValue();
          return output_(oldHash === hash ? { ok: true, registrationId: body.requestId, duplicate: true } : { ok: false, error: 'idempotency_conflict' });
        }
        const matches = sheet.getRange(2, HEADERS.length, last - 1, 1).createTextFinder(hash).matchEntireCell(true).findAll();
        for (const match of matches) {
          const previous = sheet.getRange(match.getRow(), 1, 1, 2).getValues()[0];
          if (Date.now() - Date.parse(previous[1]) < 86400000) return output_({ ok: true, registrationId: previous[0], duplicate: true });
        }
      }
      // Cache is best-effort abuse protection; never the source of deduplication truth.
      const cache = CacheService.getScriptCache();
      const bucket = Math.floor(Date.now() / 600000);
      const keys = ['alta:ip:' + body.clientKey + ':' + bucket, 'alta:global:' + bucket];
      const counts = keys.map(key => Number(cache.get(key) || 0));
      if (counts[0] >= 10 || counts[1] >= 60) return output_({ ok: false, error: 'rate_limit' });
      keys.forEach((key, i) => cache.put(key, String(counts[i] + 1), 600));
      const d = result.data;
      const row = [body.requestId, new Date().toISOString(), body.environment, d.nombre, d.cuit, d.condicionIva, d.importador || 'No aplica', d.origen, d.vieneDeCurso, d.curso || 'No aplica', d.telefono, d.email, d.domicilio, d.contactoOperacion, d.contactoAdministracion, d.asesor, hash];
      if (last >= sheet.getMaxRows()) sheet.insertRowsAfter(last, 100);
      const range = sheet.getRange(last + 1, 1, 1, HEADERS.length);
      range.setNumberFormat('@');
      // Escape spreadsheet formulas while preserving identifiers and leading zeroes.
      range.setValues([row.map(value => /^[=+\-@']/.test(value) ? "'" + value : value)]);
      SpreadsheetApp.flush();
      const saved = range.getValues()[0];
      if (saved[0] !== body.requestId || saved[HEADERS.length - 1] !== hash) return output_({ ok: false, error: 'write_unconfirmed' });
      // The final row is flushed and verified before any mail is attempted.
      // Keep the same lock as the fallback worker to prevent competing sends.
      if (body.environment === 'production') {
        try { notifySavedRegistration_(saved); }
        catch { console.error('Registration saved; notification needs review or fallback processing'); }
      }
      return output_({ ok: true, registrationId: body.requestId, duplicate: false });
    } finally { lock.releaseLock(); }
  } catch { return output_({ ok: false, error: 'persistence_unconfirmed' }); }
}
function hmac_(value, secret) { return Utilities.computeHmacSha256Signature(value, secret, Utilities.Charset.UTF_8).map(byte => ('0' + (byte & 255).toString(16)).slice(-2)).join(''); }
function equal_(a, b) { if (typeof a !== 'string' || a.length !== b.length) return false; let difference = 0; for (let i = 0; i < a.length; i++) difference |= a.charCodeAt(i) ^ b.charCodeAt(i); return difference === 0; }
function output_(payload) { return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON); }

// Send after final persistence; the timer is a fallback. Mail failure never loses a saved registration.
// Configure ALTA_CLIENTES_MAIL_TO in Script Properties; never use form input as recipients.
const MAIL_HEADERS = ['ID de alta', 'Estado', 'Destinatarios', 'Inicio (UTC)', 'Enviado (UTC)'];

function setupAltaNotifications() {
  mailRecipients_();
  const book = SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty('ALTA_CLIENTES_SHEET_ID'));
  let outbox = book.getSheetByName('Avisos de alta');
  if (!outbox) {
    outbox = book.insertSheet('Avisos de alta');
    outbox.getRange(1, 1, 1, MAIL_HEADERS.length).setValues([MAIL_HEADERS]);
    outbox.setFrozenRows(1);
  }
  verifyMailSchema_(outbox);
  // Authorize sending before installing the timer. No message is sent by setup.
  MailApp.getRemainingDailyQuota();
  if (!ScriptApp.getProjectTriggers().some(trigger => trigger.getHandlerFunction() === 'processAltaNotifications')) {
    ScriptApp.newTrigger('processAltaNotifications').timeBased().everyMinutes(1).create();
  }
}

function processAltaNotifications() { processAltaNotifications_('production'); }

// Explicit acceptance check only; does not replay other historical preview registrations.
function testAltaNotification() {
  const id = PropertiesService.getScriptProperties().getProperty('ALTA_CLIENTES_MAIL_TEST_ID');
  if (!/^[a-f\d-]{36}$/i.test(id || '')) throw new Error('Configure the acceptance registration ID first');
  processAltaNotifications_('preview', id);
}

function mailRecipients_() {
  const raw = PropertiesService.getScriptProperties().getProperty('ALTA_CLIENTES_MAIL_TO') || '';
  const addresses = [...new Set(raw.split(',').map(address => address.trim()).filter(Boolean))];
  if (!addresses.length || addresses.length > 10 || addresses.some(address => !/^[^\s@,<>]+@[^\s@,<>]+\.[^\s@,<>]+$/.test(address))) throw new Error('Invalid internal mail recipient configuration');
  return addresses;
}

function verifyMailSchema_(sheet) {
  if (!sheet || JSON.stringify(sheet.getRange(1, 1, 1, MAIL_HEADERS.length).getValues()[0]) !== JSON.stringify(MAIL_HEADERS)) throw new Error('Mail tracking sheet schema mismatch');
}

function processAltaNotifications_(environment, onlyId) {
  const recipients = mailRecipients_();
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(1000)) return;
  try {
    const book = SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty('ALTA_CLIENTES_SHEET_ID'));
    const source = book.getSheetByName('Hoja 1');
    const outbox = book.getSheetByName('Avisos de alta');
    verifyMailSchema_(outbox);
    if (!source || JSON.stringify(source.getRange(1, 1, 1, HEADERS.length).getValues()[0]) !== JSON.stringify(HEADERS)) throw new Error('Registration sheet schema mismatch');
    const tracked = outbox.getLastRow() > 1 ? outbox.getRange(2, 1, outbox.getLastRow() - 1, MAIL_HEADERS.length).getValues() : [];
    // Persisted ENVIANDO/REVISAR entries are deliberately not retried: delivery may have
    // succeeded before a timeout. This prevents silent duplicate mail after uncertain sends.
    const seen = new Set(tracked.map(row => row[0]));
    let sent = 0;
    const started = Date.now();
    for (let first = 2; first <= source.getLastRow(); first += 200) {
      const count = Math.min(200, source.getLastRow() - first + 1);
      const rows = source.getRange(first, 1, count, HEADERS.length).getValues();
      for (let index = 0; index < rows.length; index++) {
        const row = rows[index];
        if (row[2] !== environment || (onlyId && row[0] !== onlyId) || seen.has(row[0])) continue;
        if (sent >= 20 || Date.now() - started > 45000) return;
        // Quota exhaustion leaves the registration pending for a later timer execution.
        if (MailApp.getRemainingDailyQuota() < recipients.length) return;
        sendRegistrationMail_(row, book, source, outbox, recipients);
        seen.add(row[0]);
        sent++;
      }
    }
  } finally { lock.releaseLock(); }
}

// Called only while the registration handler holds the script lock.
function notifySavedRegistration_(row) {
  const recipients = mailRecipients_();
  const book = SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty('ALTA_CLIENTES_SHEET_ID'));
  const outbox = book.getSheetByName('Avisos de alta');
  verifyMailSchema_(outbox);
  const tracked = outbox.getLastRow() > 1 ? outbox.getRange(2, 1, outbox.getLastRow() - 1, 1).getValues() : [];
  if (tracked.some(entry => entry[0] === row[0]) || MailApp.getRemainingDailyQuota() < recipients.length) return;
  sendRegistrationMail_(row, book, book.getSheetByName('Hoja 1'), outbox, recipients);
}

function sendRegistrationMail_(row, book, source, outbox, recipients) {
  const message = registrationMail_(row, book.getId(), source.getSheetId());
  const mailRow = outbox.getLastRow() + 1;
  if (mailRow > outbox.getMaxRows()) outbox.insertRowsAfter(outbox.getMaxRows(), 100);
  const tracking = [row[0], 'ENVIANDO', recipients.join(', '), new Date().toISOString(), ''];
  outbox.getRange(mailRow, 1, 1, MAIL_HEADERS.length).setValues([tracking]);
  SpreadsheetApp.flush();
  try {
    MailApp.sendEmail({ to: recipients.join(','), name: 'GlobalTrip', subject: message.subject, body: message.body, htmlBody: message.htmlBody });
    tracking[1] = 'ENVIADO';
    tracking[4] = new Date().toISOString();
    outbox.getRange(mailRow, 1, 1, MAIL_HEADERS.length).setValues([tracking]);
    SpreadsheetApp.flush();
  } catch {
    tracking[1] = 'REVISAR';
    outbox.getRange(mailRow, 1, 1, MAIL_HEADERS.length).setValues([tracking]);
    SpreadsheetApp.flush();
    throw new Error('Mail delivery needs review in Avisos de alta; registration remains saved');
}
}

function registrationMail_(row, sheetId, tabId) {
  const fields = [
    ['Nombre / razón social', row[3]], ['CUIT/CUIL', row[4]], ['Condición frente al IVA', row[5]],
    ['Importador registrado en Aduana', row[6]], ['Por dónde nos conocieron', row[7]],
    ['Viene de un curso', row[8]], ['Cuál curso', row[9]], ['Teléfono', row[10]],
    ['E-mail', row[11]], ['Domicilio', row[12]], ['Contacto para avances de la operación', row[13]],
    ['Contacto para temas administrativos', row[14]], ['Asesor', row[15]]
  ];
  const escape = value => String(value == null ? '' : value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const name = String(row[3]).replace(/[\r\n]/g, ' ');
  const date = Utilities.formatDate(new Date(row[1]), 'America/Argentina/Buenos_Aires', 'dd/MM/yyyy HH:mm');
  const url = 'https://docs.google.com/spreadsheets/d/' + encodeURIComponent(sheetId) + '/edit#gid=' + tabId;
  const body = 'GLOBALTRIP — NUEVA ALTA DE CLIENTE\n\nSe registró el alta de ' + name + '.\n' + date + ' (Argentina)\n\n' + fields.map(field => field[0] + ': ' + field[1]).join('\n') + '\n\nVer registro en la hoja: ' + url;
  const htmlBody = '<!doctype html><html lang="es"><body style="margin:0;background:#f6f7fa;font-family:Arial,sans-serif;color:#171a36"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px"><tr><td align="center"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#fff;border:1px solid #e4e6ee;border-radius:16px"><tr><td style="padding:28px 32px;background:#0b0c49;color:white;border-radius:16px 16px 0 0"><div style="font-size:23px;font-weight:bold">GlobalTrip</div><div style="font-size:12px;margin-top:8px;letter-spacing:1px">AVISO INTERNO</div></td></tr><tr><td style="padding:28px 32px"><h1 style="font-size:25px;color:#0b0c49;margin:0 0 12px">Nueva alta de cliente</h1><p style="font-size:15px;line-height:1.6;margin:0 0 24px">Se registró el alta de <strong>' + escape(name) + '</strong>.<br><span style="color:#676d80;font-size:13px">' + escape(date) + ' · Argentina</span></p><table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse">' + fields.map(field => '<tr><th align="left" valign="top" style="width:46%;padding:11px 12px 11px 0;border-bottom:1px solid #eceef3;font-size:12px;font-weight:normal;color:#676d80">' + escape(field[0]) + '</th><td valign="top" style="padding:11px 0;border-bottom:1px solid #eceef3;font-size:14px;line-height:1.45;overflow-wrap:anywhere">' + escape(field[1]) + '</td></tr>').join('') + '</table><p style="margin:26px 0 8px"><a href="' + escape(url) + '" style="display:inline-block;background:#0b0c49;color:#fff;text-decoration:none;padding:14px 20px;border-radius:9px;font-size:14px;font-weight:bold">Ver registro en la hoja</a></p></td></tr></table></td></tr></table></body></html>';
  return { subject: 'Nueva alta de cliente — ' + name + ' | GlobalTrip', body, htmlBody };
}
